# coding: utf-8

"""
    Femsa API

    Femsa sdk

    The version of the OpenAPI document: 2.1.0
    Contact: engineering@femsa.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from digitalfemsa.models.checkout_order_template import CheckoutOrderTemplate
from typing import Optional, Set
from typing_extensions import Self

class Checkout(BaseModel):
    """
    Creates a Payment Link. This is a sub-resource related to an Order template: each time a customer pays using the link, the API will create an Order using `order_template`. 
    """ # noqa: E501
    name: StrictStr = Field(description="Payment link name.")
    type: StrictStr = Field(description="Checkout type.")
    recurrent: StrictBool = Field(description="false: single use. true: multiple payments")
    payments_limit_count: Optional[StrictInt] = Field(default=None, description="Required when `recurrent` is true. Maximum number of payments allowed through the link.")
    allowed_payment_methods: List[StrictStr] = Field(description="Payment methods available in the payment link.")
    needs_shipping_contact: StrictBool = Field(description="This flag allows you to fill in the shipping information at checkout.")
    starts_at: Optional[StrictInt] = Field(default=None, description="Start time for the link. Unix timestamp in seconds.")
    expires_at: StrictInt = Field(description="Expiration time for the link (Unix timestamp in seconds). Valid range is between 2 and 365 days (calculated from the next day of creation at 00:01). ")
    can_not_expire: Optional[StrictBool] = Field(default=None, description="If true, the link does not expire.")
    order_template: CheckoutOrderTemplate
    __properties: ClassVar[List[str]] = ["name", "type", "recurrent", "payments_limit_count", "allowed_payment_methods", "needs_shipping_contact", "starts_at", "expires_at", "can_not_expire", "order_template"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Checkout from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of order_template
        if self.order_template:
            _dict['order_template'] = self.order_template.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Checkout from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "type": obj.get("type"),
            "recurrent": obj.get("recurrent"),
            "payments_limit_count": obj.get("payments_limit_count"),
            "allowed_payment_methods": obj.get("allowed_payment_methods"),
            "needs_shipping_contact": obj.get("needs_shipping_contact"),
            "starts_at": obj.get("starts_at"),
            "expires_at": obj.get("expires_at"),
            "can_not_expire": obj.get("can_not_expire"),
            "order_template": CheckoutOrderTemplate.from_dict(obj["order_template"]) if obj.get("order_template") is not None else None
        })
        return _obj


