# coding: utf-8

"""
    Femsa API

    Femsa sdk

    The version of the OpenAPI document: 2.1.0
    Contact: engineering@femsa.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from digitalfemsa.models.customer_fiscal_entities_request import CustomerFiscalEntitiesRequest
from digitalfemsa.models.customer_payment_methods_request import CustomerPaymentMethodsRequest
from digitalfemsa.models.customer_shipping_contacts import CustomerShippingContacts
from typing import Optional, Set
from typing_extensions import Self

class Customer(BaseModel):
    """
    Customer create request.
    """ # noqa: E501
    name: StrictStr = Field(description="Customer's name.")
    email: StrictStr = Field(description="Customer email address.")
    phone: Optional[Annotated[str, Field(strict=True, max_length=19)]] = Field(default=None, description="Customer phone number.")
    corporate: Optional[StrictBool] = Field(default=False, description="Indicates whether the customer email is corporate.")
    custom_reference: Optional[StrictStr] = Field(default=None, description="Merchant-defined reference used to identify the customer in your system.")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Arbitrary metadata associated with the customer.")
    payment_sources: Optional[List[CustomerPaymentMethodsRequest]] = Field(default=None, description="Customer payment sources to be created with the customer (optional).")
    fiscal_entities: Optional[List[CustomerFiscalEntitiesRequest]] = Field(default=None, description="Customer fiscal entities to be created with the customer (optional).")
    shipping_contacts: Optional[List[CustomerShippingContacts]] = Field(default=None, description="Customer shipping contacts to be created with the customer (optional).")
    __properties: ClassVar[List[str]] = ["name", "email", "phone", "corporate", "custom_reference", "metadata", "payment_sources", "fiscal_entities", "shipping_contacts"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Customer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in payment_sources (list)
        _items = []
        if self.payment_sources:
            for _item in self.payment_sources:
                if _item:
                    _items.append(_item.to_dict())
            _dict['payment_sources'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in fiscal_entities (list)
        _items = []
        if self.fiscal_entities:
            for _item in self.fiscal_entities:
                if _item:
                    _items.append(_item.to_dict())
            _dict['fiscal_entities'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in shipping_contacts (list)
        _items = []
        if self.shipping_contacts:
            for _item in self.shipping_contacts:
                if _item:
                    _items.append(_item.to_dict())
            _dict['shipping_contacts'] = _items
        # set to None if phone (nullable) is None
        # and model_fields_set contains the field
        if self.phone is None and "phone" in self.model_fields_set:
            _dict['phone'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Customer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "email": obj.get("email"),
            "phone": obj.get("phone"),
            "corporate": obj.get("corporate") if obj.get("corporate") is not None else False,
            "custom_reference": obj.get("custom_reference"),
            "metadata": obj.get("metadata"),
            "payment_sources": [CustomerPaymentMethodsRequest.from_dict(_item) for _item in obj["payment_sources"]] if obj.get("payment_sources") is not None else None,
            "fiscal_entities": [CustomerFiscalEntitiesRequest.from_dict(_item) for _item in obj["fiscal_entities"]] if obj.get("fiscal_entities") is not None else None,
            "shipping_contacts": [CustomerShippingContacts.from_dict(_item) for _item in obj["shipping_contacts"]] if obj.get("shipping_contacts") is not None else None
        })
        return _obj


