# coding: utf-8

"""
    Femsa API

    Femsa sdk

    The version of the OpenAPI document: 2.1.0
    Contact: engineering@femsa.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from digitalfemsa.models.customer_fiscal_entities_response import CustomerFiscalEntitiesResponse
from digitalfemsa.models.customer_payment_methods_response import CustomerPaymentMethodsResponse
from digitalfemsa.models.customer_response_shipping_contacts import CustomerResponseShippingContacts
from typing import Optional, Set
from typing_extensions import Self

class CustomerResponse(BaseModel):
    """
    customer response
    """ # noqa: E501
    id: StrictStr = Field(description="Customer's ID")
    object: StrictStr
    created_at: StrictInt = Field(description="Creation date of the object (Unix timestamp)")
    livemode: StrictBool = Field(description="true if the object exists in live mode or false if the object exists in test mode")
    name: Optional[StrictStr] = Field(default=None, description="Customer's name")
    email: Optional[StrictStr] = None
    phone: Optional[StrictStr] = Field(default=None, description="Customer's phone number")
    corporate: Optional[StrictBool] = Field(default=None, description="true if the customer is a company")
    custom_reference: Optional[StrictStr] = Field(default=None, description="Custom reference")
    default_fiscal_entity_id: Optional[StrictStr] = None
    default_shipping_contact_id: Optional[StrictStr] = None
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Customer metadata (maps to contextual_data in backend)")
    payment_sources: Optional[CustomerPaymentMethodsResponse] = None
    fiscal_entities: Optional[CustomerFiscalEntitiesResponse] = None
    shipping_contacts: Optional[CustomerResponseShippingContacts] = None
    __properties: ClassVar[List[str]] = ["id", "object", "created_at", "livemode", "name", "email", "phone", "corporate", "custom_reference", "default_fiscal_entity_id", "default_shipping_contact_id", "metadata", "payment_sources", "fiscal_entities", "shipping_contacts"]

    @field_validator('object')
    def object_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['customer']):
            raise ValueError("must be one of enum values ('customer')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CustomerResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of payment_sources
        if self.payment_sources:
            _dict['payment_sources'] = self.payment_sources.to_dict()
        # override the default output from pydantic by calling `to_dict()` of fiscal_entities
        if self.fiscal_entities:
            _dict['fiscal_entities'] = self.fiscal_entities.to_dict()
        # override the default output from pydantic by calling `to_dict()` of shipping_contacts
        if self.shipping_contacts:
            _dict['shipping_contacts'] = self.shipping_contacts.to_dict()
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if email (nullable) is None
        # and model_fields_set contains the field
        if self.email is None and "email" in self.model_fields_set:
            _dict['email'] = None

        # set to None if phone (nullable) is None
        # and model_fields_set contains the field
        if self.phone is None and "phone" in self.model_fields_set:
            _dict['phone'] = None

        # set to None if default_fiscal_entity_id (nullable) is None
        # and model_fields_set contains the field
        if self.default_fiscal_entity_id is None and "default_fiscal_entity_id" in self.model_fields_set:
            _dict['default_fiscal_entity_id'] = None

        # set to None if default_shipping_contact_id (nullable) is None
        # and model_fields_set contains the field
        if self.default_shipping_contact_id is None and "default_shipping_contact_id" in self.model_fields_set:
            _dict['default_shipping_contact_id'] = None

        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CustomerResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "object": obj.get("object"),
            "created_at": obj.get("created_at"),
            "livemode": obj.get("livemode"),
            "name": obj.get("name"),
            "email": obj.get("email"),
            "phone": obj.get("phone"),
            "corporate": obj.get("corporate"),
            "custom_reference": obj.get("custom_reference"),
            "default_fiscal_entity_id": obj.get("default_fiscal_entity_id"),
            "default_shipping_contact_id": obj.get("default_shipping_contact_id"),
            "metadata": obj.get("metadata"),
            "payment_sources": CustomerPaymentMethodsResponse.from_dict(obj["payment_sources"]) if obj.get("payment_sources") is not None else None,
            "fiscal_entities": CustomerFiscalEntitiesResponse.from_dict(obj["fiscal_entities"]) if obj.get("fiscal_entities") is not None else None,
            "shipping_contacts": CustomerResponseShippingContacts.from_dict(obj["shipping_contacts"]) if obj.get("shipping_contacts") is not None else None
        })
        return _obj


