# coding: utf-8

"""
    Femsa API

    Femsa sdk

    The version of the OpenAPI document: 2.1.0
    Contact: engineering@femsa.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class TransactionResponse(BaseModel):
    """
    Transaction object.
    """ # noqa: E501
    id: StrictStr = Field(description="Unique identifier of the transaction.")
    object: StrictStr = Field(description="Object name, which is transaction.")
    amount: StrictInt = Field(description="The amount of the transaction.")
    fee: StrictInt = Field(description="The amount to be deducted for taxes and commissions.")
    net: StrictInt = Field(description="The net amount after deducting commissions and taxes.")
    currency: Annotated[str, Field(strict=True, max_length=3)] = Field(description="The currency of the transaction. It uses the 3-letter code of ISO 4217.")
    status: StrictStr = Field(description="Code indicating transaction status.")
    type: StrictStr = Field(description="Transaction type.")
    created_at: StrictInt = Field(description="Date and time of creation of the transaction in Unix format.")
    livemode: StrictBool = Field(description="Indicates whether the transaction was created in live mode or test mode.")
    charge: Optional[StrictStr] = Field(default=None, description="Charge ID associated with the transaction (present only if the transaction belongs to a charge).")
    transfer: Optional[StrictStr] = Field(default=None, description="Transfer ID associated with the transaction (present only if the transaction belongs to a transfer).")
    transferred_at: Optional[StrictInt] = Field(default=None, description="Date and time when the transaction was transferred, in Unix format.")
    formula: Optional[StrictStr] = Field(default=None, description="Transaction fee formula identifier (if available).")
    __properties: ClassVar[List[str]] = ["id", "object", "amount", "fee", "net", "currency", "status", "type", "created_at", "livemode", "charge", "transfer", "transferred_at", "formula"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['unprocessed', 'pending', 'available', 'owing', 'paid_out', 'on_hold', 'retained', 'voided']):
            raise ValueError("must be one of enum values ('unprocessed', 'pending', 'available', 'owing', 'paid_out', 'on_hold', 'retained', 'voided')")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['capture', 'capture_reversal', 'liquidation', 'liquidation_reversal', 'payout', 'payout_reversal', 'refund', 'refund_reversal', 'rounding_adjustment', 'transfer', 'transferred', 'retention', 'temporary_retention', 'cashout_retention', 'cashout_confirmation', 'cashout_cancelation', 'autofund_capture']):
            raise ValueError("must be one of enum values ('capture', 'capture_reversal', 'liquidation', 'liquidation_reversal', 'payout', 'payout_reversal', 'refund', 'refund_reversal', 'rounding_adjustment', 'transfer', 'transferred', 'retention', 'temporary_retention', 'cashout_retention', 'cashout_confirmation', 'cashout_cancelation', 'autofund_capture')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TransactionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if charge (nullable) is None
        # and model_fields_set contains the field
        if self.charge is None and "charge" in self.model_fields_set:
            _dict['charge'] = None

        # set to None if transfer (nullable) is None
        # and model_fields_set contains the field
        if self.transfer is None and "transfer" in self.model_fields_set:
            _dict['transfer'] = None

        # set to None if transferred_at (nullable) is None
        # and model_fields_set contains the field
        if self.transferred_at is None and "transferred_at" in self.model_fields_set:
            _dict['transferred_at'] = None

        # set to None if formula (nullable) is None
        # and model_fields_set contains the field
        if self.formula is None and "formula" in self.model_fields_set:
            _dict['formula'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TransactionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "object": obj.get("object"),
            "amount": obj.get("amount"),
            "fee": obj.get("fee"),
            "net": obj.get("net"),
            "currency": obj.get("currency"),
            "status": obj.get("status"),
            "type": obj.get("type"),
            "created_at": obj.get("created_at"),
            "livemode": obj.get("livemode"),
            "charge": obj.get("charge"),
            "transfer": obj.get("transfer"),
            "transferred_at": obj.get("transferred_at"),
            "formula": obj.get("formula")
        })
        return _obj


